#!/usr/bin/env python3

# Copyright 2026 Roberto Matarazzo
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Dev-only script: generates src/tokenomicon/currencies.py from ISO 4217 codes.

Source: `datahub.io/core/currency-codes` (consolidation of ISO 4217 tables
official A.1 "Current currency & funds" and A.3 "Historic").

Usage:
    python scripts/generate_currency_codes.py

Not intended to run at runtime or be distributed with the package:
uses only the stdlib, lives outside src/ for clarity.
"""

import csv
import io
import urllib.request
from pathlib import Path

SOURCE_URL = "https://datahub.io/core/currency-codes/r/codes-all.csv"
EXPECTED_COLUMNS = {
    "Entity",
    "Currency",
    "AlphabeticCode",
    "NumericCode",
    "MinorUnit",
    "WithdrawalDate",
}
OUTPUT_PATH = Path(__file__).parent.parent / "src" / "tokenomicon" / "currencies.py"

# Codes present in the ISO table but NOT currencies in which a
# provider bills: precious metals, test/transaction codes, and
# "funds codes" (financial accounting units, not real currencies).
EXCLUDED_CODES = frozenset({
    "XAU", "XAG", "XPD", "XPT",                             # Precious metals
    "XTS", "XXX",                                           # Test. No transaction
    "XDR", "XAD", "XBA", "XBB", "XBC", "XBD", "XSU", "XUA", # Special drawing rights (FMI)
    "BOV", "CLF", "COU",                                    # Funds code (Bolivia, Cile, Colombia)
    "CHE", "CHW",                                           # WIR Euro/Franco (complementary currency)
    "MXV", "USN", "UYI", "UYW"                              # Other known funds codes
})


def _fetch_csv() -> str:
    with urllib.request.urlopen(SOURCE_URL, timeout=30) as response:
        return response.read().decode("utf-8")


def _extract_codes(csv_text: str) -> list[str]:
    reader = csv.DictReader(io.StringIO(csv_text))

    if reader.fieldnames is None or not EXPECTED_COLUMNS.issubset(
        set(reader.fieldnames)
    ):
        raise RuntimeError(
            f"Unexpected CSV format. Expected columns: {EXPECTED_COLUMNS}, "
            f"found: {reader.fieldnames}"
        )

    codes: set[str] = set()

    for row in reader:
        code = (row.get("AlphabeticCode") or "").strip().upper()
        withdrawal_date = (row.get("WithdrawalDate") or "").strip()

        if not code or len(code) != 3:
            continue
        if withdrawal_date:
            continue
        if code in EXCLUDED_CODES:
            continue

        codes.add(code)

    return sorted(codes)


def _write_constants(codes: list[str]) -> None:
    lines = [
        "# Automatically generated by scripts/generate_currency_codes.py",
        f"# Source: {SOURCE_URL}",
        "# DO NOT edit by hand: rerun the script to update.",
        "",
        "ISO_4217_CODES: frozenset[str] = frozenset({",
    ]

    # 10 codes per line, for readability
    for i in range(0, len(codes), 10):
        chunk = codes[i : i + 10]
        lines.append("    " + ", ".join(f'"{c}"' for c in chunk) + ",")

    lines.append("})")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(codes)} codes to {OUTPUT_PATH}")


def main() -> None:
    csv_text = _fetch_csv()
    codes = _extract_codes(csv_text)
    _write_constants(codes)


if __name__ == "__main__":
    main()
